### PR TITLE
Reorganize heuristics

### PR DESCRIPTION
**Pull request by hlibbabii**
@furunkel  Do you think we can simplify keyword-heuristic-related code like this?

### CODE REVIEW

**Comment by furunkel** [comment]
Sure, I think I had performance in mind when I added the special case (i.e. `in` vs. `isdisjoint` on singleton sets).
But it simplifies things quite a bit and there may be no appreciable performance gain.
:+1: 
Where did the `lfs` list in `bug.py` go, though?

**Comment by hlibbabii** [comment]
> Where did the `lfs` list in `bug.py` go, though?

my bad! added it back

**Comment by furunkel** [comment]
An alternative would be to rename `all_lfs` to `module_lfs` and define a new `commit_lfs` method, which does `module_lfs(bug) + bug_keyword_lfs_list` ?

**Comment by hlibbabii** [comment]
> An alternative would be to rename `all_lfs` to `module_lfs` and define a new `commit_lfs` method, which does `module_lfs(bug) + bug_keyword_lfs_list` ?

yeah, could be done! I'll play around with different options and show you.

**Comment by hlibbabii** [comment]
@furunkel, what do you think about having keyword heuristics specified explicitely in the file with heuristics? Like below:

```
@keyword_labeling_functions('bug.message')
def keywords_lookup_in_message(commit: Commit, keyword_group: List[str]) -> Label:
    if keyword_group and commit.message.match(keyword_group): return Label.BUG
    return Label.ABSTAIN


@keyword_labeling_functions('bogusbugs.message')
def bogus_fix_keyword_in_message(commit: Commit, keyword_group: List[str]) -> Label:
    if 'fix' in commit.message.stems or 'bug' in commit.message.stems:
        if commit.message.match(BOGUS_FIX_KEYWORDS):
            return Label.BUGLESS
        else:
            return Label.BUG
    return Label.ABSTAIN
```

`@keyword_labeling_functions` would return a list of labeling functions. It would basically do what `keyword_lfs` does now.

**Comment by hlibbabii** [comment]
@furunkel Do you think we could also generalize `match` and `match_bigram` to `match_n_gram`? This would also simplify things quite a bit.  We could basically have one set for uni- and bi-grams. Isn't even faster to do one `isdisjoint` check?

**Comment by furunkel** [comment]
> @furunkel Do you think we could also generalize `match` and `match_bigram` to `match_n_gram`? This would also simplify things quite a bit. We could basically have one set for uni- and bi-grams. Isn't even faster to do one `isdisjoint` check?

Hm, yes. I did not think about that. You mean keeping unigrams and bigrams in a single set? :+1: 

> @furunkel, what do you think about having keyword heuristics specified explicitely in the file with heuristics? Like below:
> 
> ```
> @keyword_labeling_functions('bug.message')
> def keywords_lookup_in_message(commit: Commit, keyword_group: List[str]) -> Label:
>     if keyword_group and commit.message.match(keyword_group): return Label.BUG
>     return Label.ABSTAIN
> 
> 
> @keyword_labeling_functions('bogusbugs.message')
> def bogus_fix_keyword_in_message(commit: Commit, keyword_group: List[str]) -> Label:
>     if 'fix' in commit.message.stems or 'bug' in commit.message.stems:
>         if commit.message.match(BOGUS_FIX_KEYWORDS):
>             return Label.BUGLESS
>         else:
>             return Label.BUG
>     return Label.ABSTAIN
> ```
> 
> `@keyword_labeling_functions` would return a list of labeling functions. It would basically do what `keyword_lfs` does now.

Not sure how this would pan out in the future, maybe we can defer this until we have LFs for more than a single task?

**Comment by hlibbabii** [comment]
@furunkel , talking about multiple tasks. What do you think about the following approach for having a hierarchy of tasks and labels:

```
>>> class CommitBugginess(IntFlag):
...     BUG = 0b11110000
...     BUGLESS = 0b00001111
...     REFACTORING = 0b00001100
...     ENHANCEMENT = 0b00000011
...     CONCURRENCY_BUG = 0b10000000
...     BOGUS_BUG = 0b00010000
...
>>>
>>> def heuristic1():
...     return CommitBugginess.REFACTORING
...
>>> def heuristic2():
...     return CommitBugginess.BUG
...
>>> def heuristic3():
...     return CommitBugginess.BOGUS_BUG
...
>>> def heuristic4():
...     return CommitBugginess.CONCURRENCY_BUG
...
>>>
>>> def lf_applier(lfs: List[Callable], categories: Set[CommitBugginess]):
...     print(f"Classifying into the following categories: {categories}")
...     for lf in lfs:
...         produced_label = lf()
...         for category in categories:
...             if produced_label & category != 0:
...                 print(f'{lf.__name__}: {category}')
...                 break
...
>>>
>>> lf_applier([heuristic1, heuristic2, heuristic3, heuristic4], {CommitBugginess.BUG, CommitBugginess.BUGLESS})
Classifying into the following categories: {<CommitBugginess.BUG: 240>, <CommitBugginess.BUGLESS: 15>}
heuristic1: 15
heuristic2: 240
heuristic3: 240
heuristic4: 240
```

So the idea is to have fine-grained labels and then we can be flexible in choosing what classifier we wan to build, bug vs bugless, refactoring vs everything else, etc. I am using `IntFlag` class and binary numbers for now to illustrate the idea better, haven't come up with a proper data structure in python for that yet. What do you think?

**Comment by hlibbabii** [comment]
@furunkel , also do you think its a good idea if a labeling function returns multiple labels, e.g. tangled changes and bugless, as opposed to having to identical functions in different files which would only differ by the label they return?

**Comment by hlibbabii** [comment]
@furunkel , with the last commit I split the heuristics into message/ issues/ changes based. So that we can calculate and compare stats between these types (will be the next commit). When doing that it happened naturally that I had to do something with the keywords, so I organized them so far using `keyword_labeling_functions` annotation. I know that you are not sure if this approach is good enough, so I have no problems changing it back if you think it's better as it used to be.

**Review by furunkel — COMMENTED** [review]
The `keyword_labeling_functions` as a decorator looks a bit strange IMHO, other than that :+1:
I mean, it can stay this way for now and we can see where things go... 
Since the structure of the smaller sample is very different we either need to clinch this before making adaptations for that or update this PR after, which would be more work I guess?

As for the hierarchy, Snorkel does not really support them, AFAIK. What is possible, though, is grouping finer labels (i.e. types of bugs) into a general label (e.g. bug) after Snorkel did its thing.
BTW, is the NOBUG label (and related LFs) seems unnecessary? It's simply `not(BUG)`, which we get for free?

**Comment by hlibbabii** [comment]
> The `keyword_labeling_functions` as a decorator looks a bit strange IMHO, other than that 👍
> I mean, it can stay this way for now and we can see where things go...
> Since the structure of the smaller sample is very different we either need to clinch this before making adaptations for that or update this PR after, which would be more work I guess?

Does it make sense to have a call to talk about it tomorrow before the general call? What was the reason for changing the structure for the smaller sample, btw?


> As for the hierarchy, Snorkel does not really support them, AFAIK. What is possible, though, is grouping finer labels (i.e. types of bugs) into a general label (e.g. bug) after Snorkel did its thing.

This is something that I was thinking about with the only difference of grouping them BEFORE feeding to snorkel. Basically, when creating heuristics and deciding which labels they assign, we want to be as precise and fine-grained as possible so that we cover as many classification tasks as possible without needing to adjust heuristics later.

**Comment by furunkel** [comment]
> This is something that I was thinking about with the only difference of grouping them BEFORE feeding to snorkel. Basically, when creating heuristics and deciding which labels they assign, we want to be as precise and fine-grained as possible so that we cover as many classification tasks as possible without needing to adjust heuristics later.

Ok. Why would we want to group them before Snorkel, though? I consider the labeling functions as part of Snorkel, so that might cause some confusion. 
 

> Does it make sense to have a call to talk about it tomorrow before the general call? What was the reason for changing the structure for the smaller sample, btw?

Sure, can't hurt. The sample contains random commits from the full 50GB dataset; so with the current structure you would need to have the entire `/files/` and `/issues/` stuff in place (which is possible, but large). So I pulled only the subset of issues and files out of there that are actually referenced, and put then in single files.

**Comment by hlibbabii** [comment]
> Ok. Why would we want to group them before Snorkel, though? I consider the labeling functions as part of Snorkel, so that might cause some confusion.

if we want to build a classifier bug vs non-bug, why do we need snorkel to learn how to differentiate between concurrency bug and ui-bug (for example)?

> The sample contains random commits from the full 50GB dataset; so with the current structure you would need to have the entire /files/ and /issues/ stuff in place (which is possible, but large). So I pulled only the subset of issues and files out of there that are actually referenced, and put them in single files.

Of course, why did you have to put them in a single file though? Couldn't preserve the same structure but have fewer files?

Which time would be good for you tomorrow morning?

**Comment by hlibbabii** [comment]
Not sure if these are the results that we want:

|Heuristic groups|	Metric|	Value|
|-----|----------|-----------|
|message|	label_model_acc_1151_commits|	0.79583|
|message+issues|	label_model_acc_1151_commits|	0.79583|
|message+issues+files|	label_model_acc_1151_commits|	0.78193|	

|Path|	Metric|	Value|
|-----|----------|-----------|
|message|	label_model_acc_herzig|	0.71653|
|message+issues|	label_model_acc_herzig|	0.71577|
|message+issues+files|	label_model_acc_herzig|	0.70253|

|Path|	Metric|	Value|
|-----|----------|-----------|
|message|	label_model_acc_berger|	0.76|
|message+issues|	label_model_acc_berger|	0.76|
|message+issues+files|	label_model_acc_berger|	0.77333|

**Comment by furunkel** [comment]
Is that for b_b? The sample is on the bohr-dataset release page BTW.
Tomorrow morning is a bit bad, after noon if you want, otherwise we can just talk about it during the meeting.

**Comment by hlibbabii** [comment]
> Is that for b_b? The sample is on the bohr-dataset release page BTW.
> Tomorrow morning is a bit bad, after noon if you want, otherwise we can just talk about it during the meeting.

Yes, this is for b_b first 100k rows. Alright, let's do it during the meeting then.

**Pull request merged**
